name = "miniserver"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "MIT OR Apache-2.0"
website = ""
tags = []

executables = ["main"]

#[[actions]]
#type = "post-build"
#command = ["gnatprove", "-P", "miniserver.gpr"]

[[depends-on]]
gnatprove = "^12.1.1"
epoll = "~0.1.1"
json = "^5.0.3"

[[pins]]
epoll = { path='../epoll-ada' }

[build-profiles]
"*" = "development"

[build-switches]
release.optimization = ["-O3", "-gnatn", "-gnatp", "-march=native"]
development.optimization = ["-Og"]

[[depends-on]]
chests = "~0.1.1"
